urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import os

from web.urls import urlpatterns as web_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += web_urls

if os.getenv('DJANGO_SETTINGS_MODULE') == 'settings.development':
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models/photo.py
from django.db import models

from core.models.base import BaseModel
from core.models.specimen import Specimen
from core.models.user import User


class Photo(BaseModel):
    class Meta:
        app_label = 'core'
        default_permissions = ()
        db_table = 'photos'

    def _upload_to_path(self, filename):
        return f"photos/{self.specimen.box.id}/{filename}"

    specimen = models.ForeignKey(Specimen, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True)
    mime = models.CharField(max_length=100)
    path = models.ImageField(upload_to=_upload_to_path)
    happened_at = models.DateTimeField(null=True)
    description = models.TextField(null=True)

core/models/specimen.py
from enum import Enum

from django.db import models
from django.urls import reverse
from django.utils import formats

from core.models.base import BaseModel
from core.models.boxes import Box
from core.models.organism import Organism
from core.models.user import User


class GenderChoice(Enum):
    MALE = "Male"
    FEMALE = "Female"


class Specimen(BaseModel):
    class Meta:
        app_label = 'core'
        default_permissions = ()
        db_table = 'specimens'

    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    box = models.ForeignKey(Box, on_delete=models.CASCADE)
    organism = models.ForeignKey(Organism, on_delete=models.CASCADE)
    gender = models.CharField(max_length=10, choices=[(tag.value, tag.value) for tag in GenderChoice], null=True)
    form = models.CharField(max_length=50)
    happened_at = models.DateField(null=True)
    notes = models.TextField(null=True)
    dna = models.TextField(null=True)

    def __str__(self):
        return self.organism.name

    @property
    def summary(self) -> dict:
        return {
            'id': self.id,
            'creator': str(self.creator),
            'organism__name': self.organism.name,
            'box__title': self.box.title,
            'gender': self.gender,
            'form': self.form,
            'happened_at': formats.date_format(self.happened_at),
            'notes': self.notes,
            'dna': self.dna,
            "url": reverse('specimens-detail', None, [self.id])
        }

web/forms/specimen.py
from django.forms import ModelForm

from core.models import Specimen


class SpecimenForm(ModelForm):
    class Meta:
        model = Specimen
        fields = ['box', 'organism', 'happened_at', 'form', 'gender', 'notes', 'dna']

web/views/specimens.py
import qrcode
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.forms import model_to_dict
from django.http import JsonResponse, Http404, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from core import status
from core.models import Specimen, Box, Organism
from core.models.specimen import GenderChoice
from web.forms.specimen import SpecimenForm


@login_required
def overview(request):
    if request.is_ajax():
        search = request.GET.get('search', '')
        offset = int(request.GET.get('page', 0)) + 1
        limit = int(request.GET.get('limit', 10))

        # Sorting
        sort = request.GET.get('sort', 'organism__name')
        if request.GET.get('order', 'asc') == 'desc':
            sort = f"-{sort}"

        specimens = Specimen.objects \
            .filter(organism__name__icontains=search) \
            .order_by(sort)
        paginator = Paginator(specimens, limit)

        response = {
            'rows': [row.summary for row in paginator.get_page(offset)],
            'total': paginator.count
        }

        return JsonResponse(response)

    return render(request, 'specimens/overview.html')


@login_required
def add(request):
    if request.is_ajax() and request.GET.get('type', False):
        return _process_select2(request)

    if request.method == 'GET':
        specimen_form = SpecimenForm()
        return render(request, 'specimens/form.html', {
            'form': specimen_form
        })
    elif request.method == 'POST':
        specimen = Specimen()
        specimen.creator = request.user
        specimen_form = SpecimenForm(request.POST, instance=specimen)

        if specimen_form.is_valid():
            specimen_form.save()
            return redirect('specimens-detail', specimen.id)

        return render(request, 'specimens/form.html', {
            'form': specimen_form
        }, status=status.HTTP_422_UNPROCESSABLE_ENTITY)

    raise Http404()


@login_required
def edit(request, id):
    try:
        specimen = Specimen.objects.get(pk=str(id))
    except Specimen.DoesNotExist:
        raise Http404()

    if request.is_ajax() and request.GET.get('type', False):
        return _process_select2(request)

    if request.method == 'GET':
        specimen_form = SpecimenForm(initial=model_to_dict(specimen))
        return render(request, 'specimens/form.html', {
            'form': specimen_form,
            'specimen': specimen
        })
    elif request.method == 'POST':
        specimen_form = SpecimenForm(request.POST, instance=specimen)

        if specimen_form.is_valid():
            specimen_form.save()
            return redirect('specimens-detail', specimen.id)

        return render(request, 'specimens/form.html', {
            'form': specimen_form,
            'specimen': specimen
        }, status=status.HTTP_422_UNPROCESSABLE_ENTITY)

    raise Http404()


def detail(request, id):
    try:
        specimen = Specimen.objects.get(pk=str(id))
    except Specimen.DoesNotExist:
        raise Http404()

    context = {
        'specimen': specimen
    }

    return render(request, 'specimens/detail.html', context)


@login_required
def remove(request, id):
    try:
        specimen = Specimen.objects.get(pk=str(id))
    except Specimen.DoesNotExist:
        raise Http404()

    specimen.delete()

    return redirect('specimens-overview')


def qr(request, id):
    try:
        specimen = Specimen.objects.get(pk=str(id))
    except Specimen.DoesNotExist:
        raise Http404()

    img = qrcode.make(request.build_absolute_uri(reverse('specimens-detail', None, [specimen.id])))

    response = HttpResponse(content_type="image/png")
    img.save(response, "PNG")
    return response


def _process_select2(request):
    """
    TODO: sprav na to nejaky servis/helper, takto to je neskutocne trapne
    :param request:
    :return:
    """
    search = request.GET.get('search', '')
    offset = int(request.GET.get('page', 1))
    limit = int(request.GET.get('limit', 10))
    selected = request.GET.get('selected', None)
    result = []

    if request.GET.get('type') == 'box':
        if selected:
            item = Box.objects.get(pk=selected)

            return JsonResponse({
                'items': [{
                    'id': str(item.id),
                    'text': str(item)
                }],
                'pagination': {
                    'more': False
                }
            })

        items = Box.objects.filter(title__icontains=search).order_by('title')

    elif request.GET.get('type') == 'organism':
        if selected:
            item = Organism.objects.get(pk=selected)

            return JsonResponse({
                'items': [{
                    'id': str(item.id),
                    'text': str(item)
                }],
                'pagination': {
                    'more': False
                }
            })

        items = Organism.objects.filter(name__icontains=search).order_by('name')
    elif request.GET.get('type') == 'gender':
        if selected:
            return JsonResponse({
                'items': [{
                    'id': selected,
                    'text': selected,
                    'selected': True
                }],
                'pagination': {
                    'more': False
                }
            })

        for tag in GenderChoice:
            result.append({
                'id': tag.value,
                'text': tag.value
            })
        return JsonResponse({
            'items': result,
            'pagination': {
                'more': False
            }
        })
    else:
        raise Http404()

    paginator = Paginator(items, limit)

    for row in paginator.get_page(offset):
        result.append({
            'id': str(row.id),
            'text': str(row)
        })

    return JsonResponse({
        'items': result,
        'pagination': {
            'more': paginator.get_page(offset).has_next()
        }
    })

templates/specimens/detail.html
{% extends '_layouts/base.html' %}

{% load i18n %}
{% load social %}

{% block title %}{{ specimen.organism.name }}{% endblock %}

{% block content %}
	<div class="container">

		<div class="row pt-3">
			<div class="col-lg-8">
				<h1>{{ specimen.organism.name }}</h1>
			</div>
			<div class="col-lg-4 text-right">
				<a
					class="btn btn-danger"
					role="button"
					href="{% url 'specimens-remove' specimen.id %}"
				>
					<i class="fas fa-trash"></i> {% trans 'Remove specimen' %}
				</a>

				<a
					class="btn btn-primary"
					role="button"
					href="{% url 'specimens-edit' specimen.id %}"
				>
					<i class="fas fa-edit"></i> {% trans 'Edit specimen' %}
				</a>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-4">
				<div class="card">
					<img class="card-img-top" src="{% url 'specimens-qr' specimen.id %}" alt="Specimen QR code">
					<div class="card-body">
						<h5 class="card-title">{{ specimen.organism.name }}</h5>
						<h6 class="card-subtitle mb-2 text-muted">
							{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.name }}
						</h6>
						<div class="card-text">
							<ul class="list-unstyled">
								<li>
									<strong>{% trans 'Happened at' %}: </strong>
									{{ specimen.happened_at }}
								</li>
								<li>
									<strong>{% trans 'Form' %}: </strong>
									{{ specimen.form }}
								</li>
								<li>
									<strong>{% trans 'Gender' %}: </strong>
									{{ specimen.gender }}
								</li>
							</ul>
						</div>
					</div>

					<div class="list-group list-group-flush">
						<a href="{% url 'boxes-detail' specimen.box.id %}" class="list-group-item list-group-item-action">
							<i class="fas fa-box"></i> Box
						</a>

						<a
							href="{{ specimen.organism.name|wikipedia }}"
							rel="external"
							target="_blank"
							class="list-group-item list-group-item-action"
						>
							<i class="fab fa-wikipedia-w"></i> Wikipedia
						</a>
					</div>
				</div>
			</div>

			<div class="col-lg-8">

				<div class="row">
					<div class="col-lg-5">
						<h5>{% trans 'Taxonomy' %}</h5>
						<ul class="list-unstyled">
							<li>
								<strong>{% trans 'Kingdom' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.taxonomic_phylum.kingdom.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.taxonomic_phylum.kingdom.name }}
								</a>
							</li>
							<li>
								<strong>{% trans 'Phylum' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.taxonomic_phylum.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.taxonomic_phylum.name }}
								</a>
							</li>
							<li>
								<strong>{% trans 'Class' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.taxonomic_class.name }}
								</a>
							</li>
							<li>
								<strong>{% trans 'Order' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.taxonomic_order.name }}
								</a>
							</li>
							<li>
								<strong>{% trans 'Family' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.taxonomic_family.name }}
								</a>
							</li>
							<li>
								<strong>{% trans 'Genus' %}: </strong>
								<a
									href="{{ specimen.organism.taxonomic_species.taxonomic_genus.name|wikipedia }}"
									rel="external"
									target="_blank"
								>
									{{ specimen.organism.taxonomic_species.taxonomic_genus.name }}
								</a>
							</li>
						</ul>
					</div>

					<div class="col-lg-7">
						<h5>{% trans 'DNA' %}</h5>
						<p>
							{{ specimen.dna }}
						</p>

						<h5>{% trans 'Notes' %}</h5>
						<p>
							{{ specimen.notes }}
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12">
						<h2>{% trans "Photos" %}</h2>
						{% for photo in specimen.photo_set.all %}
							<a href="{% url 'photos-detail' photo.id %}" data-toggle="modal" data-target="#ajaxModal">
								<figure class="figure" style="max-width: 200px;">
									<img src="{{ photo.path.url }}" class="figure-img img-fluid img-thumbnail" alt="{{ photo.title }}">
									<figcaption class="figure-caption text-center">{{ photo.title }}</figcaption>
								</figure>
							</a>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

	{% include '_partials/modal.html' with modal_size='modal-lg' %}
{% endblock %}

{% block javascript %}
{% endblock %}

templates/specimens/form.html
{% extends '_layouts/base.html' %}

{% load i18n %}

{% block title %}{% trans 'Add specimen' %}{% endblock %}

{% block content %}
	<div class="container">

		<div class="row pt-3">
			<div class="col-lg-8">
				<h1>
					<i class="fas fa-spider"></i>
					{% trans 'Add specimen' %}
				</h1>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<form
					method="post"
					action="{% if specimen %}{% url 'specimens-edit' specimen.id %}{% else %}{% url 'specimens-add' %}{% endif %}"
				>
					{% csrf_token %}
					{% include '_partials/bootstrap/form.html' with form=form %}

					<div class="form-group text-right">
						<button type="submit" class="btn btn-primary">
						<i class="fas fa-save"></i> {% trans 'Save' %}
					</button>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block javascript %}
	<script>

		function prefillSelect(element) {
			let selectElement = $(element);

			$.ajax({
				type: 'GET',
				url: window.location,
				data: {
					'selected': selectElement.data('selected'),
					'type': selectElement.attr('name')
				}
			}).then(function (data) {
				let option = new Option(data.items[0].text, data.items[0].id, true, true);
				selectElement.append(option).trigger('change');
				selectElement.trigger({
					type: 'select2:select',
					params: {
						data: data
					}
				});
			});
		}

		$(window).on('load', function () {
			prefillSelect("#id_box");
			prefillSelect("#id_organism");
			prefillSelect("#id_gender");
		});
	</script>
{% endblock %}

templates/specimens/overview.html
{% extends '_layouts/base.html' %}

{% load i18n %}

{% block title %}{% trans 'Specimens' %}{% endblock %}

{% block content %}
	<div class="container">

		<div class="row pt-3">
			<div class="col-lg-8">
				<h1>
					<i class="fas fa-spider"></i>
					{% trans 'Specimens' %}
				</h1>
			</div>
			<div class="col-lg-4 text-right">
				<a
					class="btn btn-primary"
					role="button"
					href="{% url 'specimens-add' %}"
				>
					<i class="fas fa-plus"></i> {% trans 'Add specimen' %}
				</a>
			</div>
		</div>


		<div class="row">
			<div class="col-lg-12">
				<table
					class="table"
					id="dataTable"
					data-toggle="table"
					data-search="true"
					data-ajax="loadTable"
					data-row-attributes="rowAttributes"
					data-side-pagination="server"
					data-pagination="true"
					data-id-field="id"
					data-unique-id="id"
				>
					<thead>
					<tr>
						<th data-field="organism__name" data-sortable="true">{% trans 'Organism' %}</th>
						<th data-field="box__title" data-sortable="true">{% trans 'Box' %}</th>
						<th data-field="gender" data-sortable="true">{% trans 'Gender' %}</th>
						<th data-field="form" data-sortable="true">{% trans 'Form' %}</th>
						<th data-field="happened_at" data-sortable="true">{% trans 'Happened at' %}</th>
					</tr>
					</thead>
					<tbody></tbody>
				</table>
			</div>
		</div>


	</div>
{% endblock %}

{% block javascript %}
	<script>
		function loadTable(params) {
			$.ajax({
				type: "GET",
				url: "{% url 'specimens-overview' %}",
				dataType: "json",
				data: params.data,
				success: function (data) {
					params.success({
						"rows": data.rows,
						"total": data.total
					})
				},
				error: function (err) {
					params.error(err);
				}
			})
		}

		function rowAttributes(row, index) {
			return {
				'data-url': row.url,
				'id': row.id
			}
		}

		$("#dataTable tbody").on('click', 'tr[data-url]', function (e) {
			window.location = $(this).data('url');
		});
	</script>
{% endblock %}